<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="5" ignored="0" total="6" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-07T18:19:35 IST" name="Suite" finished-at="2022-04-07T18:21:03 IST" duration-ms="87502">
    <groups>
      <group name="regression">
        <method signature="PracticeRertyAnalyzerListener1.createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" name="createNewOrganizatinTest" class="com.crm.testngpractice.PracticeRertyAnalyzerListener1"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="PracticeRertyAnalyzerListener1.createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" name="createNewOrganizatinTest" class="com.crm.testngpractice.PracticeRertyAnalyzerListener1"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2022-04-07T18:19:35 IST" name="Test" finished-at="2022-04-07T18:21:03 IST" duration-ms="87502">
      <class name="com.crm.testngpractice.PracticeRertyAnalyzerListener1">
        <test-method is-config="true" signature="openDataBase()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:33 IST" name="openDataBase" finished-at="2022-04-07T18:19:35 IST" duration-ms="2014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDataBase -->
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:36 IST" name="launchBrowser" finished-at="2022-04-07T18:19:40 IST" duration-ms="4543" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:40 IST" name="loginToApplication" finished-at="2022-04-07T18:19:45 IST" duration-ms="5169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:45 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:19:52 IST" duration-ms="7132" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:52 IST" name="logoutFromApplication" finished-at="2022-04-07T18:19:54 IST" duration-ms="2050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:54 IST" name="loginToApplication" finished-at="2022-04-07T18:19:59 IST" duration-ms="4456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:19:59 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:20:06 IST" duration-ms="7061" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:06 IST" name="logoutFromApplication" finished-at="2022-04-07T18:20:08 IST" duration-ms="2515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:08 IST" name="loginToApplication" finished-at="2022-04-07T18:20:12 IST" duration-ms="4011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:12 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:20:20 IST" duration-ms="7221" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:20 IST" name="logoutFromApplication" finished-at="2022-04-07T18:20:22 IST" duration-ms="2116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:22 IST" name="loginToApplication" finished-at="2022-04-07T18:20:26 IST" duration-ms="4448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:26 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:20:33 IST" duration-ms="6526" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:33 IST" name="logoutFromApplication" finished-at="2022-04-07T18:20:35 IST" duration-ms="1909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:35 IST" name="loginToApplication" finished-at="2022-04-07T18:20:38 IST" duration-ms="3758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method retried="true" signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:38 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:20:46 IST" duration-ms="7362" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:46 IST" name="logoutFromApplication" finished-at="2022-04-07T18:20:48 IST" duration-ms="1797" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="loginToApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:48 IST" name="loginToApplication" finished-at="2022-04-07T18:20:52 IST" duration-ms="4395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method signature="createNewOrganizatinTest()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:20:52 IST" name="createNewOrganizatinTest" finished-at="2022-04-07T18:21:00 IST" duration-ms="8155" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.testngpractice.PracticeRertyAnalyzerListener1.createNewOrganizatinTest(PracticeRertyAnalyzerListener1.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewOrganizatinTest -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:21:00 IST" name="logoutFromApplication" finished-at="2022-04-07T18:21:03 IST" duration-ms="2206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:21:03 IST" name="closeBrowser" finished-at="2022-04-07T18:21:03 IST" duration-ms="317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeDBconnection()[pri:0, instance:com.crm.testngpractice.PracticeRertyAnalyzerListener1@3c7f66c4]" started-at="2022-04-07T18:21:03 IST" name="closeDBconnection" finished-at="2022-04-07T18:21:03 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBconnection -->
      </class> <!-- com.crm.testngpractice.PracticeRertyAnalyzerListener1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
